### ISSUE TITLE
Question on releases with Java strategy

### ISSUE THREAD

**Issue by SamC-Apadmi** [googleapis/release-please-action#1007]
I've just started using manifest config for release-please. I have three components using the java strategy, the others just use the simple strategy. (Config is here: https://github.com/Apadmi-Engineering/Mockzilla/blob/develop/release-please-config.json).

My question is this; release-please is opening a PR which bumps the java versions to a new SNAPSHOT, but there's no PR for the actual next release. How do I do a full release? Presumably not by merging the SNAPSHOT PR?

I assumed I'd get two PRs, one for SNAPSHOT and one for a full release?

This is the only PR I have currently: https://github.com/Apadmi-Engineering/Mockzilla/pull/99

I'd appreciate some guidance since I'm not sure I'm using the action correctly.

**Comment by chingor13** [comment]
Often in a java project, the working branch should always be a `-SNAPSHOT` version to support nightly/snapshot builds. Release-please will think that you need a snapshot version in the target branch if the current version isn't a snapshot. If your branch is on a snapshot and has releasable changes, then it will propose the next non-snapshot version.
