### ISSUE TITLE
Failing to use CC's seems to cause the changes in the commit to be ignored when generating releases

### ISSUE THREAD

**Issue by wesleytodd** [googleapis/release-please-action#1042]
#### Environment details

  - Programming language: JS
  - OS: n/a
  - Language runtime version: n/a
  - Package version: n/a

#### Steps to reproduce

Commits not following CCs have now twice not generated releases for us while ones which do work as expected. In the logs we see the following:

```
Building candidate release pull request for path: packages/turbo-task
❯ type: node
❯ targetBranch: main
❯ commit could not be parsed: 9dd27740f2cc17b6467f3327aaa09dec1296131f add support for newt vars and remove log order grouping (#225)
❯ commits: 0
✔ Considering: 0 commits
✔ No commits for path: packages/turbo-task, skipping
```

Despite that commit having changes to two applicable packages:

```
$git --no-pager show --name-only 9dd27740f2cc17b6467f3327aaa09dec1296131f
commit 9dd27740f2cc17b6467f3327aaa09dec1296131f (main)
Author: <redacted>
Date:   Mon Oct 7 16:11:31 2024 -0700

    add support for newt vars and remove log order grouping (#225)

packages/turbo-task/lib/task.js
plugins/plugin-turbo/turbo-json.js
```

**Comment by wesleytodd** [comment]
It is possible this is miss-attributed to the commit format and that log. We found another case where it was happening with the `chore:` prefix. May need some more debugging to see why this commit (and a few others) are not being correctly detected while others are.

**Comment by aaronware** [comment]
@wesleytodd how did you get the release to happen after the fact? I see one of our commits in a project has a typo but I am not sure how to resolve it. Any shove in the right direction would be greatly appreciated. We tried a CC formatted commit after the typo was merged but it's basically stuck and wont parse any commits any more CC formatted or not

**Comment by wesleytodd** [comment]
Yeah, I never fully tracked it down and then it stopped happening for us so I left it without a deep dive. It was particularly happening to one user on a few PRs so I thought maybe there was something in their config, but even that stopped happening so I am not sure. What I did to un-block it was rev the versions in the manifest to force a re-release in our CI and that part worked. Sorry I am not more help, I will close this since it seemed to have resolved.
