### ISSUE TITLE
Due to the move this action is no longer a verified action

### ISSUE THREAD

**Issue by DuncanCasteleyn** [googleapis/release-please-action#986]
Due to the move this action is no longer a verified action.

> \[Error\] googleapis/release-please-action is not allowed to be used in *redacted*/workflows. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: *redacted*.

_Originally posted by @DuncanCasteleyn in https://github.com/googleapis/release-please-action/issues/980#issuecomment-2106846228_

Like I reported in another issue, this action is no longer verified since being moved however at my client not all actions are allowed to run and they need to be verified to be used or added to an exclusion list with a pinned version, this means that updating requires me to go through an approval progress each time, verification makes this action easier for me to upgrade and is probably required by other organizations as well.

I'm creating this issue to track the progress on getting this action verified again. See https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by DuncanCasteleyn** [comment]
Can we get an ETA when this action wel become verified again? I think I'm not the only one waiting for this.

**Comment by shinebayar-g** [comment]
Looks like it was verified recently?

![image](https://github.com/googleapis/release-please-action/assets/3091558/69eb375f-5b74-44b4-b15f-6c4bc5fbe54d)

**Comment by DuncanCasteleyn** [comment]
Thanks for letting me know, I will close this issue then.
