### ISSUE TITLE
Not creating GitHub releases after PR has been merged

### ISSUE THREAD

**Issue by abhi-markan** [googleapis/release-please-action#999]
After the automatic release please PR has been created and merged the PR label stays on `autorelease: pending` and not to `autorelease: tagged` and release is not created in GitHub however files are updated with correct version number.

#### Environment details

  - Programming language: Node.js although using `npx release-please`
  - OS: Linux (GitHub Actions)
  - Language runtime version: Node 20.11.1
  - Package version: 16.10.2

#### Steps to reproduce

  1. Create a release please PR (after merge to base branch), using command `npx release-please release-pr --token=123 --repo-url=https://github.com/${{ github.repository }} --release-type=node`
  2. Merge PR
  3. `package*.json`, `manifest.json`, `CHANGELOG.md` files are updated
  4. However GitHub releases are not created.

**Comment by farshadniayeshpour** [comment]
I also have this issue.

**Comment by AlexanderBrevig** [comment]
I just spent quite a few hours pulling my hair out. We solved it by simply removing the label and rerunning the workflow.

**Comment by chingor13** [comment]
If you are using the CLI, there are 2 separate commands - `release-pr` and `github-release`. After merging, the Release PR, you need to run the `github-release` command which will take the release and fix the tags.

If you have further issues, please open the issue on https://github.com/googleapis/release-please as this repo is for the GitHub action implementation.
